name: Task
description: A specific, implementable piece of work
title: "[TASK] <title>"
labels: ["task"]
projects: ["sk8meet/1"]
type: "Task"
body:
  - type: markdown
    attributes:
      value: |
        ## Task Details
        Tasks should be small enough to be completed in 1-3 days by a single developer.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear description of what needs to be done
      placeholder: Implement the user registration form...
    validations:
      required: true
      
  - type: input
    id: epic
    attributes:
      label: Related Epic
      description: Which epic does this task belong to? (Use the issue number, e.g., #123)
      placeholder: "#123"
    validations:
      required: false
      
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Specific, testable criteria that must be met for this task to be considered complete
      placeholder: |
        - [ ] Registration form includes email, password, and confirm password fields
        - [ ] Form validates email format
        - [ ] Passwords must be at least 8 characters
        - [ ] Success message appears on successful submission
    validations:
      required: true
      
  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What type of work is involved?
      options:
        - Feature Implementation
        - Bug Fix
        - Refactoring
        - Documentation
        - Testing
        - DevOps
    validations:
      required: true
      
  - type: dropdown
    id: area
    attributes:
      label: Technical Area
      description: Which part of the system does this task primarily affect?
      options:
        - Frontend (React/Next.js)
        - Backend (Node.js/Express)
        - Database (PostgreSQL/Prisma)
        - DevOps (Docker/Kubernetes)
        - Full Stack
    validations:
      required: true
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Any technical details or suggestions for implementation
      placeholder: Consider using the Material-UI form components...
    validations:
      required: false
      
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work is involved?
      options:
        - Small (< 1 day)
        - Medium (1-2 days)
        - Large (2-3 days)
    validations:
      required: true
      
  - type: textarea
    id: testing
    attributes:
      label: Testing Notes
      description: How should this task be tested?
      placeholder: |
        - Test with valid and invalid email formats
        - Verify password validation works
        - Check error messages display correctly
    validations:
      required: false